name: Publish Blog Content

on:
  workflow_dispatch:    # لتشغيل يدوي من GitHub
  schedule:
    - cron: '0 * * * *'  # تشغيل كل ساعة (يمكنك تعديل الجدولة)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser requests

    - name: Run blog.py script
      run: python blog.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add news/*.md
        git diff --cached --quiet || git commit -m "تحديث محتوى المدونة تلقائيًا"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
